# azure-pipelines.yml
pool:
  vmImage: 'macOS 10.13'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '9.7.1'
  displayName: 'Install Node'
- script: npm install
  displayName: 'Install dependencies'
- script: |
    cd ios
    bundle install
    fastlane build
  displayName: 'Build iOS'
- script: |
    cd android
    bundle install
    fastlane build
  displayName: 'Build android'