# azure-pipelines.yml
pool:
  vmImage: 'macOS-10.15'
steps:
- task: NodeTool@0
  displayName: 'Install Node'
  inputs:
    versionSpec: '12.16.1'
- script: yarn install
  displayName: 'Install dependencies'
- script: yarn run test
  displayName: 'Run testing'
# - script: yarn run ios
#   displayName: 'Run ios'
# - script: yarn run android
#   displayName: 'Run android'